import {
	daysAgo,
	daysAhead,
	EVENTS,
	monthsAgo,
	monthsAhead,
	prisma,
} from "./helpers";

export async function seedEvents() {
	const events = [
		// Event 1: Large wedding, PLANNING, future
		{
			id: EVENTS.WEDDING,
			ownerId: "usr_owner_001",
			name: "Casamento Ana & Carlos",
			type: "WEDDING" as const,
			status: "PLANNING" as const,
			eventDate: monthsAhead(4),
			startTime: "15:00",
			endTime: "02:00",
			venueName: "Convento de São Francisco",
			address: "Rua Major Kanhangulo",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Maianga",
			reference: "Próximo ao Hospital Central",
			latitude: -8.8399,
			longitude: 13.2894,
			capacity: 250,
			limitGuestCapacity: true,
			currency: "AOA",
			description:
				"Casamento civil e religioso com recepção no jardim do convento.",
		},
		// Event 2: Medium engagement, CONFIRMED, near future
		{
			id: EVENTS.ENGAGEMENT,
			ownerId: "usr_partner_002",
			name: "Noivado Beatriz & David",
			type: "ENGAGEMENT" as const,
			status: "CONFIRMED" as const,
			eventDate: monthsAhead(1),
			startTime: "18:00",
			endTime: "23:00",
			venueName: "Clube Mineiro",
			address: "Rua dos Enganos",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Miramar",
			capacity: 120,
			limitGuestCapacity: false,
			currency: "AOA",
			description:
				"Festa de noivado intimista com familiares e amigos próximos.",
		},
		// Event 3: Small birthday, CONFIRMED, today
		{
			id: EVENTS.BIRTHDAY,
			ownerId: "usr_owner_001",
			name: "Aniversário de Ricardo",
			type: "BIRTHDAY" as const,
			status: "CONFIRMED" as const,
			eventDate: new Date(),
			startTime: "19:00",
			endTime: "01:00",
			venueName: "Restaurante O Cantinho",
			address: "Rua Comandante Gika",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Alvalade",
			capacity: 50,
			limitGuestCapacity: false,
			currency: "AOA",
			description: "Festa de aniversário surpresa com amigos e família.",
		},
		// Event 4: Large conference, COMPLETED, past
		{
			id: EVENTS.CONFERENCE,
			ownerId: "usr_admin_003",
			name: "Conferência TechAngola 2026",
			type: "CONFERENCE" as const,
			status: "COMPLETED" as const,
			eventDate: monthsAgo(2),
			startTime: "08:00",
			endTime: "18:00",
			venueName: "Centro de Convenções de Luanda",
			address: "Marginal da Luanda",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Kinaxixi",
			capacity: 200,
			limitGuestCapacity: false,
			currency: "AOA",
			description: "Conferência anual de tecnologia e inovação em Angola.",
		},
		// Event 5: Medium wedding, CANCELLED, future
		{
			id: EVENTS.WEDDING_CANCELLED,
			ownerId: "usr_admin_003",
			name: "Casamento Silva & Santos",
			type: "WEDDING" as const,
			status: "CANCELLED" as const,
			eventDate: monthsAhead(6),
			startTime: "16:00",
			endTime: "00:00",
			venueName: "Palácio da Facunda",
			address: "Estrada da Facunda",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Viana",
			capacity: 180,
			limitGuestCapacity: true,
			currency: "AOA",
			description: "Casamento cancelado por motivos familiares.",
		},
		// Event 6: Empty graduation, DRAFT, far future
		{
			id: EVENTS.GRADUATION,
			ownerId: "usr_owner_001",
			name: "Formatura Universitária",
			type: "GRADUATION" as const,
			status: "DRAFT" as const,
			eventDate: monthsAhead(8),
			startTime: "10:00",
			endTime: "16:00",
			venueName: null,
			address: null,
			province: null,
			municipality: null,
			neighborhood: null,
			capacity: 100,
			limitGuestCapacity: false,
			currency: "AOA",
			description: "Cerimónia de formatura — pending venue confirmation.",
		},
		// Event 7: Small corporate dinner, PLANNING, soon
		{
			id: EVENTS.CORPORATE,
			ownerId: "usr_partner_002",
			name: "Jantar Corporativo Empresarial",
			type: "CORPORATE" as const,
			status: "PLANNING" as const,
			eventDate: daysAhead(14),
			startTime: "19:30",
			endTime: "23:00",
			venueName: "Hotel Epic Sana",
			address: "Rua da Missão",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Miramar",
			capacity: 80,
			limitGuestCapacity: true,
			currency: "AOA",
			description:
				"Jantar de confraternização da empresa com colegas e parceiros.",
		},
		// Event 8: Medium workshop, CONFIRMED, near future
		{
			id: EVENTS.WORKSHOP,
			ownerId: "usr_editor_004",
			name: "Workshop de Criatividade",
			type: "WORKSHOP" as const,
			status: "CONFIRMED" as const,
			eventDate: daysAhead(21),
			startTime: "09:00",
			endTime: "17:00",
			venueName: "Hub de Criatividade",
			address: "Rua Comandante Gika",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Samba",
			capacity: 40,
			limitGuestCapacity: true,
			currency: "AOA",
			description: "Workshop intensivo de design thinking e criatividade.",
		},
		// Event 9: Small baby shower, COMPLETED, past
		{
			id: EVENTS.BABY_SHOWER,
			ownerId: "usr_admin_003",
			name: "Festa de Embalar da Maria",
			type: "BABY_SHOWER" as const,
			status: "COMPLETED" as const,
			eventDate: monthsAgo(1),
			startTime: "15:00",
			endTime: "20:00",
			venueName: "Jardim da Tia Graça",
			address: "Rua 5 de Outubro",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Ingombota",
			capacity: 30,
			limitGuestCapacity: false,
			currency: "AOA",
			description:
				"Festa de embalar para a pequena Maria — tema rosa e branco.",
		},
		// Event 10: Large ceremony, PLANNING, far future
		{
			id: EVENTS.CEREMONY,
			ownerId: "usr_owner_001",
			name: "Cerimónia Religiosa de São Pedro",
			type: "CEREMONY" as const,
			status: "PLANNING" as const,
			eventDate: monthsAhead(5),
			startTime: "09:00",
			endTime: "13:00",
			venueName: "Igreja de São Pedro",
			address: "Rua dos Mártires",
			province: "Luanda",
			municipality: "Luanda",
			neighborhood: "Cidade Alta",
			capacity: 300,
			limitGuestCapacity: false,
			currency: "AOA",
			description:
				"Cerimónia religiosa solene com recepção no salão paroquial.",
		},
	];

	for (const e of events) {
		await prisma.event.upsert({
			where: { id: e.id },
			update: {},
			create: e,
		});
	}
	console.log(`  ✅ Events (${events.length})`);

	return events;
}
