import { daysAgo, daysAhead, EVENTS, prisma } from "./helpers";

export async function seedGuests() {
	// ── WEDDING (80 guests) ────────────────────────────────────────────
	const weddingGuests = [
		// FAMILY (18)
		{
			id: "gst_wed_001",
			name: "Maria da Conceição Santos",
			phone: "+244 923 456 789",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_002",
			name: "António Carlos Santos",
			phone: "+244 923 456 790",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_003",
			name: "Teresa Margarida Santos",
			phone: "+244 923 456 791",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_004",
			name: "João Pedro Ferreira",
			phone: "+244 923 456 792",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_005",
			name: "Ana Beatriz Ferreira",
			phone: "+244 923 456 793",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_006",
			name: "Carlos Eduardo Mendes",
			phone: "+244 923 456 794",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_007",
			name: "Fernanda Lúcia Mendes",
			phone: "+244 923 456 795",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_008",
			name: "Paulo Sérgio Oliveira",
			phone: "+244 923 456 796",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_009",
			name: "Marta Cristina Oliveira",
			phone: "+244 923 456 797",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_010",
			name: "Ricardo Daniel Gomes",
			phone: "+244 923 456 798",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "PENDING",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_011",
			name: "Helena Sofia Gomes",
			phone: "+244 923 456 799",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_012",
			name: "Miguel Ângelo Pires",
			phone: "+244 923 456 800",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_013",
			name: "Sofia Inês Pires",
			phone: "+244 923 456 801",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_014",
			name: "Rui Alexandre Tavares",
			phone: "+244 923 456 802",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "DECLINED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_015",
			name: "Cláudia Manuela Tavares",
			phone: "+244 923 456 803",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_016",
			name: "Fernando José Rodrigues",
			phone: "+244 923 456 804",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_017",
			name: "Laura Santos Silva",
			phone: "+244 923 456 805",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_018",
			name: "André Luís Silva",
			phone: "+244 923 456 806",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		// FRIENDS (25)
		{
			id: "gst_wed_019",
			name: "Lucas Henrique Almeida",
			phone: "+244 923 456 807",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_020",
			name: "Patrícia Cristina Araújo",
			phone: "+244 923 456 808",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_021",
			name: "Gabriel Nuno Costa",
			phone: "+244 923 456 809",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_022",
			name: "Raquel Filipa Costa",
			phone: "+244 923 456 810",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_023",
			name: "Diogo André Marques",
			phone: "+244 923 456 811",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_024",
			name: "Inês Carolina Marques",
			phone: "+244 923 456 812",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_025",
			name: "Tomás Rafael Neto",
			phone: "+244 923 456 813",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_026",
			name: "Catarina Sofia Neto",
			phone: "+244 923 456 814",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_027",
			name: "Pedro Henrique Lopes",
			phone: "+244 923 456 815",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "MAYBE",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_028",
			name: "Beatriz Marina Lopes",
			phone: "+244 923 456 816",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_029",
			name: "Nuno Alexandre Barros",
			phone: "+244 923 456 817",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_030",
			name: "Vanessa Rute Barros",
			phone: "+244 923 456 818",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_031",
			name: "Rafael Domingos Machado",
			phone: "+244 923 456 819",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_032",
			name: "Mariana Teresa Machado",
			phone: "+244 923 456 820",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_033",
			name: "Sérgio Paulo Reis",
			phone: "+244 923 456 821",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_034",
			name: "Daniela Isabel Reis",
			phone: "+244 923 456 822",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_035",
			name: "Francisco Xavier Vieira",
			phone: "+244 923 456 823",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "WAITING",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_036",
			name: "Sara Luísa Vieira",
			phone: "+244 923 456 824",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_037",
			name: "Alexandre Tiago Fonseca",
			phone: "+244 923 456 825",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_038",
			name: "Joana Patrícia Fonseca",
			phone: "+244 923 456 826",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_039",
			name: "Bruno Filipe Santos",
			phone: "+244 923 456 827",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_040",
			name: "Letícia Avelino Santos",
			phone: "+244 923 456 828",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_041",
			name: "Tiago Nuno Gaspar",
			phone: "+244 923 456 829",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_042",
			name: "Carla Vanessa Gaspar",
			phone: "+244 923 456 830",
			group: "Amigos da Universidade",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_043",
			name: "Vasco Miguel Ribeiro",
			phone: "+244 923 456 831",
			group: "Amigos da Infância",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		// COLLEAGUES (15)
		{
			id: "gst_wed_044",
			name: "Roberto Carlos Monteiro",
			phone: "+244 923 456 832",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_045",
			name: "Adriana Cristina Monteiro",
			phone: "+244 923 456 833",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_046",
			name: "Marcos Rui Delgado",
			phone: "+244 923 456 834",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_047",
			name: "Sandra Marina Delgado",
			phone: "+244 923 456 835",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_048",
			name: "Hugo Daniel Pinto",
			phone: "+244 923 456 836",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_049",
			name: "Camila Fernanda Pinto",
			phone: "+244 923 456 837",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_050",
			name: "Renato Sérgio Lopes",
			phone: "+244 923 456 838",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_051",
			name: "Mónica Saraiva Lopes",
			phone: "+244 923 456 839",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_052",
			name: "Luís Fernando Cardoso",
			phone: "+244 923 456 840",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_053",
			name: "Raquel Inês Cardoso",
			phone: "+244 923 456 841",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_054",
			name: "Fábio André Teixeira",
			phone: "+244 923 456 842",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_055",
			name: "Ana Rita Teixeira",
			phone: "+244 923 456 843",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_056",
			name: "Vítor Hugo Nascimento",
			phone: "+244 923 456 844",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_057",
			name: "Patrícia Mãe Nascimento",
			phone: "+244 923 456 845",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_058",
			name: "Eduardo Manuele Braga",
			phone: "+244 923 456 846",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		// VIP (5)
		{
			id: "gst_wed_059",
			name: "Dr. António Manuel da Silva",
			phone: "+244 923 456 847",
			group: "Padrinhos",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_060",
			name: "Dra. Helena Cristina da Silva",
			phone: "+244 923 456 848",
			group: "Padrinhos",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_061",
			name: "Eng. Manuel de Sousa",
			phone: "+244 923 456 849",
			group: "Padrinhos",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_062",
			name: "Dra. Sónia Maria de Sousa",
			phone: "+244 923 456 850",
			group: "Padrinhos",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_063",
			name: "Dr. Carlos Alberto Mendonça",
			phone: "+244 923 456 851",
			group: "Padrinhos",
			type: "VIP",
			status: "PENDING",
			companionsLimit: 1,
		},
		// OTHER (17)
		{
			id: "gst_wed_064",
			name: "José Eduardo MPLA",
			phone: "+244 923 456 852",
			group: "Vizinhos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_065",
			name: "Teresa Cristina MPLA",
			phone: "+244 923 456 853",
			group: "Vizinhos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_066",
			name: "Manuel Augusto Diogo",
			phone: "+244 923 456 854",
			group: "Vizinhos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_067",
			name: "Maria José Diogo",
			phone: "+244 923 456 855",
			group: "Vizinhos",
			type: "OTHER",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_068",
			name: "Paulo Alexandre Geraldo",
			phone: "+244 923 456 856",
			group: "Vizinhos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_069",
			name: "Raquel Irene Geraldo",
			phone: "+244 923 456 857",
			group: "Vizinhos",
			type: "OTHER",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_070",
			name: "Fernando da Silva Neto",
			phone: "+244 923 456 858",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_071",
			name: "Marta Regina Pires",
			phone: "+244 923 456 859",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_072",
			name: "Nelson Horácio Bastos",
			phone: "+244 923 456 860",
			group: "Conhecidos",
			type: "OTHER",
			status: "PENDING",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_073",
			name: "Sílvia Marisa Bastos",
			phone: "+244 923 456 861",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_074",
			name: "Octávio Sebastião Jardim",
			phone: "+244 923 456 862",
			group: "Conhecidos",
			type: "OTHER",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_075",
			name: "Liliana Vanessa Jardim",
			phone: "+244 923 456 863",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_076",
			name: "Renato Marcos Tomás",
			phone: "+244 923 456 864",
			group: "Conhecidos",
			type: "OTHER",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_077",
			name: "Célia Cristina Moreira",
			phone: "+244 923 456 865",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_wed_078",
			name: "Hélio Domingos Kambala",
			phone: "+244 923 456 866",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_wed_079",
			name: "Fátima Antónia Kambala",
			phone: "+244 923 456 867",
			group: "Conhecidos",
			type: "OTHER",
			status: "PENDING",
			companionsLimit: 2,
		},
		{
			id: "gst_wed_080",
			name: "Samuel Bento Lukamba",
			phone: "+244 923 456 868",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
	];

	const weddingCompanions = [
		{
			id: "gc_001",
			guestId: "gst_wed_001",
			name: "Rosa Maria Santos",
			status: "CONFIRMED",
		},
		{
			id: "gc_002",
			guestId: "gst_wed_004",
			name: "Fernanda Ferreira",
			status: "CONFIRMED",
		},
		{
			id: "gc_003",
			guestId: "gst_wed_004",
			name: "Paulo Ferreira Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_004",
			guestId: "gst_wed_006",
			name: "Teresa Mendes",
			status: "CONFIRMED",
		},
		{
			id: "gc_005",
			guestId: "gst_wed_008",
			name: "Cláudia Oliveira",
			status: "PENDING",
		},
		{
			id: "gc_006",
			guestId: "gst_wed_010",
			name: "Patrícia Gomes",
			status: "CONFIRMED",
		},
		{
			id: "gc_007",
			guestId: "gst_wed_012",
			name: "Sofia Pires",
			status: "CONFIRMED",
		},
		{
			id: "gc_008",
			guestId: "gst_wed_012",
			name: "Miguel Pires Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_009",
			guestId: "gst_wed_014",
			name: "Raquel Tavares",
			status: "DECLINED",
		},
		{
			id: "gc_010",
			guestId: "gst_wed_016",
			name: "Helena Rodrigues",
			status: "CONFIRMED",
		},
		{
			id: "gc_011",
			guestId: "gst_wed_018",
			name: "Catarina Silva",
			status: "CONFIRMED",
		},
		{
			id: "gc_012",
			guestId: "gst_wed_019",
			name: "Ana Almeida",
			status: "CONFIRMED",
		},
		{
			id: "gc_013",
			guestId: "gst_wed_021",
			name: "Marta Costa",
			status: "CONFIRMED",
		},
		{
			id: "gc_014",
			guestId: "gst_wed_023",
			name: "Joana Marques",
			status: "CONFIRMED",
		},
		{
			id: "gc_015",
			guestId: "gst_wed_023",
			name: "Diogo Marques Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_016",
			guestId: "gst_wed_025",
			name: "Filipa Neto",
			status: "CONFIRMED",
		},
		{
			id: "gc_017",
			guestId: "gst_wed_027",
			name: "Rita Lopes",
			status: "MAYBE",
		},
		{
			id: "gc_018",
			guestId: "gst_wed_029",
			name: "Sara Barros",
			status: "CONFIRMED",
		},
		{
			id: "gc_019",
			guestId: "gst_wed_032",
			name: "André Machado",
			status: "CONFIRMED",
		},
		{
			id: "gc_020",
			guestId: "gst_wed_033",
			name: "Claudia Reis",
			status: "CONFIRMED",
		},
		{
			id: "gc_021",
			guestId: "gst_wed_033",
			name: "Sérgio Reis Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_022",
			guestId: "gst_wed_035",
			name: "Helena Vieira",
			status: "WAITING",
		},
		{
			id: "gc_023",
			guestId: "gst_wed_037",
			name: "Mariana Fonseca",
			status: "CONFIRMED",
		},
		{
			id: "gc_024",
			guestId: "gst_wed_039",
			name: "Pedro Santos",
			status: "PENDING",
		},
		{
			id: "gc_025",
			guestId: "gst_wed_042",
			name: "Nuno Gaspar",
			status: "CONFIRMED",
		},
		{
			id: "gc_026",
			guestId: "gst_wed_044",
			name: "Fátima Monteiro",
			status: "CONFIRMED",
		},
		{
			id: "gc_027",
			guestId: "gst_wed_046",
			name: "Ana Delgado",
			status: "CONFIRMED",
		},
		{
			id: "gc_028",
			guestId: "gst_wed_048",
			name: "Hugo Pinto Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_029",
			guestId: "gst_wed_048",
			name: "Marta Pinto",
			status: "CONFIRMED",
		},
		{
			id: "gc_030",
			guestId: "gst_wed_050",
			name: "Teresa Lopes",
			status: "CONFIRMED",
		},
		{
			id: "gc_031",
			guestId: "gst_wed_052",
			name: "Patrícia Cardoso",
			status: "CONFIRMED",
		},
		{
			id: "gc_032",
			guestId: "gst_wed_054",
			name: "Sofia Teixeira",
			status: "CONFIRMED",
		},
		{
			id: "gc_033",
			guestId: "gst_wed_057",
			name: "Carlos Nascimento",
			status: "CONFIRMED",
		},
		{
			id: "gc_034",
			guestId: "gst_wed_059",
			name: "Helena da Silva",
			status: "CONFIRMED",
		},
		{
			id: "gc_035",
			guestId: "gst_wed_061",
			name: "Manuel de Sousa Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_036",
			guestId: "gst_wed_063",
			name: "Sónia Mendonça",
			status: "PENDING",
		},
		{
			id: "gc_037",
			guestId: "gst_wed_064",
			name: "Teresa MPLA",
			status: "CONFIRMED",
		},
		{
			id: "gc_038",
			guestId: "gst_wed_066",
			name: "Manuel Diogo Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_039",
			guestId: "gst_wed_066",
			name: "Rita Diogo",
			status: "CONFIRMED",
		},
		{
			id: "gc_040",
			guestId: "gst_wed_068",
			name: "Célia Geraldo",
			status: "CONFIRMED",
		},
		{
			id: "gc_041",
			guestId: "gst_wed_070",
			name: "Fernanda Neto",
			status: "CONFIRMED",
		},
		{
			id: "gc_042",
			guestId: "gst_wed_072",
			name: "Nelson Bastos Jr.",
			status: "PENDING",
		},
		{
			id: "gc_043",
			guestId: "gst_wed_075",
			name: "Hélio Jardim",
			status: "CONFIRMED",
		},
		{
			id: "gc_044",
			guestId: "gst_wed_077",
			name: "Marcos Moreira",
			status: "CONFIRMED",
		},
		{
			id: "gc_045",
			guestId: "gst_wed_079",
			name: "Fátima Kambala Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_046",
			guestId: "gst_wed_079",
			name: "Samuel Kambala",
			status: "CONFIRMED",
		},
	];

	// ── ENGAGEMENT (40 guests) ─────────────────────────────────────────
	const engagementGuests = [
		// FAMILY (12)
		{
			id: "gst_eng_001",
			name: "Dona Graça Mbande",
			phone: "+244 923 456 869",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_002",
			name: "Eduardo Mbande",
			phone: "+244 923 456 870",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_003",
			name: "Sandra Mbande",
			phone: "+244 923 456 871",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_004",
			name: "Dona Conceição Fernando",
			phone: "+244 923 456 872",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_005",
			name: "Paulo Fernando",
			phone: "+244 923 456 873",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_006",
			name: "Rita Fernando",
			phone: "+244 923 456 874",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_007",
			name: "Nelson Mbande",
			phone: "+244 923 456 875",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_eng_008",
			name: "Carla Mbande",
			phone: "+244 923 456 876",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_009",
			name: "Vicente Fernando",
			phone: "+244 923 456 877",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "DECLINED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_010",
			name: "Marta Fernando",
			phone: "+244 923 456 878",
			group: "Família do Noivo",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_011",
			name: "António Mbande Jr.",
			phone: "+244 923 456 879",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_012",
			name: "Luísa Mbande",
			phone: "+244 923 456 880",
			group: "Família da Noiva",
			type: "FAMILY",
			status: "WAITING",
			companionsLimit: 0,
		},
		// FRIENDS (15)
		{
			id: "gst_eng_013",
			name: "André Cambunda",
			phone: "+244 923 456 881",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_014",
			name: "Tânia Cambunda",
			phone: "+244 923 456 882",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_015",
			name: "Mário Sebastião",
			phone: "+244 923 456 883",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_016",
			name: "Fátima Sebastião",
			phone: "+244 923 456 884",
			group: "Amigos",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_017",
			name: "Domingos Kituxi",
			phone: "+244 923 456 885",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_eng_018",
			name: "Ana Kituxi",
			phone: "+244 923 456 886",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_019",
			name: "Samuel Caconda",
			phone: "+244 923 456 887",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_020",
			name: "Rosa Caconda",
			phone: "+244 923 456 888",
			group: "Amigos",
			type: "FRIEND",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_021",
			name: "Pedro Massano",
			phone: "+244 923 456 889",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_022",
			name: "Célia Massano",
			phone: "+244 923 456 890",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_023",
			name: "João Lukamba",
			phone: "+244 923 456 891",
			group: "Amigos",
			type: "FRIEND",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_024",
			name: "Mariana Lukamba",
			phone: "+244 923 456 892",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_025",
			name: "Ricardo Teta",
			phone: "+244 923 456 893",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_026",
			name: "Helena Teta",
			phone: "+244 923 456 894",
			group: "Amigos",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_027",
			name: "Nuno Gourgel",
			phone: "+244 923 456 895",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		// COLLEAGUES (8)
		{
			id: "gst_eng_028",
			name: "Francisco Chivamba",
			phone: "+244 923 456 896",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_029",
			name: "Sara Chivamba",
			phone: "+244 923 456 897",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_030",
			name: "Manuel Tomás",
			phone: "+244 923 456 898",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_031",
			name: "Brenda Tomás",
			phone: "+244 923 456 899",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_032",
			name: "Paulo Kassoma",
			phone: "+244 923 456 900",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_033",
			name: "Sonia Kassoma",
			phone: "+244 923 456 901",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_034",
			name: "Elias Gaspar",
			phone: "+244 923 456 902",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_035",
			name: "Teresa Gaspar",
			phone: "+244 923 456 903",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		// VIP (3)
		{
			id: "gst_eng_036",
			name: "Padre José Manuel",
			phone: "+244 923 456 904",
			group: "Padrinhos",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_037",
			name: "Dra. Ana Paula Cunha",
			phone: "+244 923 456 905",
			group: "Padrinhos",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_eng_038",
			name: "Dr. Rui Cunha",
			phone: "+244 923 456 906",
			group: "Padrinhos",
			type: "VIP",
			status: "PENDING",
			companionsLimit: 0,
		},
		// OTHER (2)
		{
			id: "gst_eng_039",
			name: "Carolina Machado",
			phone: "+244 923 456 907",
			group: "Conhecidos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_eng_040",
			name: "Fernando Kinta",
			phone: "+244 923 456 908",
			group: "Conhecidos",
			type: "OTHER",
			status: "DECLINED",
			companionsLimit: 1,
		},
	];

	const engagementCompanions = [
		{
			id: "gc_047",
			guestId: "gst_eng_001",
			name: "Eduardo Mbande Sr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_048",
			guestId: "gst_eng_003",
			name: "Pedro Mbande",
			status: "CONFIRMED",
		},
		{
			id: "gc_049",
			guestId: "gst_eng_005",
			name: "Conceição Fernando Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_050",
			guestId: "gst_eng_007",
			name: "Nelson Mbande Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_051",
			guestId: "gst_eng_007",
			name: "Sandra Mbande Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_052",
			guestId: "gst_eng_009",
			name: "Marta Fernando Jr.",
			status: "DECLINED",
		},
		{
			id: "gc_053",
			guestId: "gst_eng_011",
			name: "António Mbande III",
			status: "CONFIRMED",
		},
		{
			id: "gc_054",
			guestId: "gst_eng_013",
			name: "Tânia Cambunda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_055",
			guestId: "gst_eng_015",
			name: "Mário Sebastião Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_056",
			guestId: "gst_eng_017",
			name: "Domingos Kituxi Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_057",
			guestId: "gst_eng_017",
			name: "Ana Kituxi Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_058",
			guestId: "gst_eng_019",
			name: "Samuel Caconda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_059",
			guestId: "gst_eng_021",
			name: "Célia Massano Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_060",
			guestId: "gst_eng_024",
			name: "Mariana Lukamba Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_061",
			guestId: "gst_eng_026",
			name: "Nuno Teta",
			status: "PENDING",
		},
		{
			id: "gc_062",
			guestId: "gst_eng_028",
			name: "Francisco Chivamba Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_063",
			guestId: "gst_eng_030",
			name: "Manuel Tomás Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_064",
			guestId: "gst_eng_033",
			name: "Paulo Kassoma Jr.",
			status: "MAYBE",
		},
		{
			id: "gc_065",
			guestId: "gst_eng_035",
			name: "Elias Gaspar Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_066",
			guestId: "gst_eng_037",
			name: "Rui Cunha Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_067",
			guestId: "gst_eng_040",
			name: "Fernando Kinta Jr.",
			status: "DECLINED",
		},
	];

	// ── BIRTHDAY (30 guests) ───────────────────────────────────────────
	const birthdayGuests = [
		// FAMILY (10)
		{
			id: "gst_bth_001",
			name: "Dona Esperança Kuenda",
			phone: "+244 923 456 909",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_002",
			name: "Joaquim Kuenda",
			phone: "+244 923 456 910",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_003",
			name: "Fernanda Kuenda",
			phone: "+244 923 456 911",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_004",
			name: "Paulo Kuenda",
			phone: "+244 923 456 912",
			group: "Família",
			type: "FAMILY",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_005",
			name: "Teresa Kuenda",
			phone: "+244 923 456 913",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_bth_006",
			name: "Nelson Kuenda",
			phone: "+244 923 456 914",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_007",
			name: "Sara Kuenda",
			phone: "+244 923 456 915",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_008",
			name: "Ricardo Kuenda",
			phone: "+244 923 456 916",
			group: "Família",
			type: "FAMILY",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_009",
			name: "Ana Kuenda",
			phone: "+244 923 456 917",
			group: "Família",
			type: "FAMILY",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_010",
			name: "Marcos Kuenda",
			phone: "+244 923 456 918",
			group: "Família",
			type: "FAMILY",
			status: "WAITING",
			companionsLimit: 0,
		},
		// FRIENDS (12)
		{
			id: "gst_bth_011",
			name: "Cláudia Pembele",
			phone: "+244 923 456 919",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_012",
			name: "Diogo Pembele",
			phone: "+244 923 456 920",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_013",
			name: "Sofia Gingeira",
			phone: "+244 923 456 921",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 2,
		},
		{
			id: "gst_bth_014",
			name: "Rafael Gingeira",
			phone: "+244 923 456 922",
			group: "Amigos",
			type: "FRIEND",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_015",
			name: "Letícia Cassule",
			phone: "+244 923 456 923",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_016",
			name: "Tomás Cassule",
			phone: "+244 923 456 924",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_017",
			name: "Mariana Tchingunji",
			phone: "+244 923 456 925",
			group: "Amigos",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_018",
			name: "Pedro Tchingunji",
			phone: "+244 923 456 926",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_019",
			name: "Raquel Burity",
			phone: "+244 923 456 927",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_020",
			name: "Gabriel Burity",
			phone: "+244 923 456 928",
			group: "Amigos",
			type: "FRIEND",
			status: "DECLINED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_021",
			name: "Catarina Nguenca",
			phone: "+244 923 456 929",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_022",
			name: "Alexandre Nguenca",
			phone: "+244 923 456 930",
			group: "Amigos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		// COLLEAGUES (5)
		{
			id: "gst_bth_023",
			name: "Rui Pimenta",
			phone: "+244 923 456 931",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_024",
			name: "Sandra Pimenta",
			phone: "+244 923 456 932",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_025",
			name: "Fábio Quinaz",
			phone: "+244 923 456 933",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_026",
			name: "Ana Quinaz",
			phone: "+244 923 456 934",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_027",
			name: "Hugo Duma",
			phone: "+244 923 456 935",
			group: "Trabalho",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 1,
		},
		// OTHER (3)
		{
			id: "gst_bth_028",
			name: "Lurdes da Silva",
			phone: "+244 923 456 936",
			group: "Vizinhos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_bth_029",
			name: "Ricardo da Silva",
			phone: "+244 923 456 937",
			group: "Vizinhos",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 1,
		},
		{
			id: "gst_bth_030",
			name: "Marta Faria",
			phone: "+244 923 456 938",
			group: "Conhecidos",
			type: "OTHER",
			status: "MAYBE",
			companionsLimit: 0,
		},
	];

	const birthdayCompanions = [
		{
			id: "gc_068",
			guestId: "gst_bth_001",
			name: "Joaquim Kuenda Sr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_069",
			guestId: "gst_bth_003",
			name: "Paulo Kuenda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_070",
			guestId: "gst_bth_005",
			name: "Nelson Kuenda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_071",
			guestId: "gst_bth_005",
			name: "Ana Kuenda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_072",
			guestId: "gst_bth_007",
			name: "Sara Kuenda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_073",
			guestId: "gst_bth_008",
			name: "Ricardo Kuenda Jr.",
			status: "DECLINED",
		},
		{
			id: "gc_074",
			guestId: "gst_bth_009",
			name: "Ana Kuenda Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_075",
			guestId: "gst_bth_011",
			name: "Cláudia Pembele Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_076",
			guestId: "gst_bth_013",
			name: "Sofia Gingeira Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_077",
			guestId: "gst_bth_013",
			name: "Rafael Gingeira Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_078",
			guestId: "gst_bth_015",
			name: "Tomás Cassule Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_079",
			guestId: "gst_bth_018",
			name: "Pedro Tchingunji Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_080",
			guestId: "gst_bth_020",
			name: "Gabriel Burity Jr.",
			status: "DECLINED",
		},
		{
			id: "gc_081",
			guestId: "gst_bth_022",
			name: "Alexandre Nguenca Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_082",
			guestId: "gst_bth_024",
			name: "Rui Pimenta Jr.",
			status: "CONFIRMED",
		},
		{
			id: "gc_083",
			guestId: "gst_bth_027",
			name: "Hugo Duma Jr.",
			status: "WAITING",
		},
		{
			id: "gc_084",
			guestId: "gst_bth_029",
			name: "Lurdes da Silva Jr.",
			status: "CONFIRMED",
		},
	];

	// ── CONFERENCE (150 guests) ────────────────────────────────────────
	const conferenceGuests = [
		// COLLEAGUES (120) — mostly with emails
		{
			id: "gst_con_001",
			name: "Eng. Carlos Moniz",
			email: "carlos.moniz@sonangol.co.ao",
			phone: "+244 923 456 939",
			group: "Palestrantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_002",
			name: "Dra. Ana Moniz",
			email: "ana.moniz@sonangol.co.ao",
			phone: "+244 923 456 940",
			group: "Palestrantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_003",
			name: "Prof. João Van-Dúnem",
			email: "joao.vandunem@unitel.co.ao",
			phone: "+244 923 456 941",
			group: "Palestrantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_004",
			name: "Dr. Rui Mendes",
			email: "rui.mendes@bfa.co.ao",
			phone: "+244 923 456 942",
			group: "Organização",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_005",
			name: "Eng. Paulo Safeca",
			email: "paulo.safeca@bp.co.ao",
			phone: "+244 923 456 943",
			group: "Organização",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_006",
			name: "Dra. Sónia Guerra",
			email: "sonia.guerra@angolaenergy.co.ao",
			phone: "+244 923 456 944",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_007",
			name: "Eng. Manuel Bravo",
			email: "manuel.bravo@taag.co.ao",
			phone: "+244 923 456 945",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_008",
			name: "Prof. Teresa Neto",
			email: "teresa.neto.uan@edu.ao",
			phone: "+244 923 456 946",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_009",
			name: "Dr. Carlos Alberto",
			email: "carlos.alberto@bci.co.ao",
			phone: "+244 923 456 947",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_010",
			name: "Eng. Nuno Neto",
			email: "nuno.neto@unitel.co.ao",
			phone: "+244 923 456 948",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_011",
			name: "Dra. Cristina Jambeiro",
			email: "cristina.jambeiro@efitel.co.ao",
			phone: "+244 923 456 949",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_012",
			name: "Eng. Pedro Pinto",
			email: "pedro.pinto@refriango.co.ao",
			phone: "+244 923 456 950",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_013",
			name: "Prof. André Mazivumo",
			email: "andre.mazivumo@iscp.co.ao",
			phone: "+244 923 456 951",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_014",
			name: "Dr. Nelson Bernardino",
			email: "nelson.bernardino@bppra.co.ao",
			phone: "+244 923 456 952",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_015",
			name: "Eng. Marcos Cassupia",
			email: "marcos.cassupia@sonangol.co.ao",
			phone: "+244 923 456 953",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_016",
			name: "Dra. Luísa Cossa",
			email: "luisa.cossa@angolaseg.co.ao",
			phone: "+244 923 456 954",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_017",
			name: "Eng. Francisco Kasengele",
			email: "francisco.kasengele@bfa.co.ao",
			phone: "+244 923 456 955",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_018",
			name: "Prof. Sandra Tomás",
			email: "sandra.tomas@ucan.co.ao",
			phone: "+244 923 456 956",
			group: "Academia",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_019",
			name: "Dr. Vicente Lando",
			email: "vicente.lando@bci.co.ao",
			phone: "+244 923 456 957",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_020",
			name: "Eng. Rita Pinto de Carvalho",
			email: "rita.carvalho@unitel.co.ao",
			phone: "+244 923 456 958",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_021",
			name: "Dra. Tânia Borges",
			email: "tania.borges@angolamining.co.ao",
			phone: "+244 923 456 959",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_022",
			name: "Eng. Hélio Dias",
			email: "helio.dias@bp.co.ao",
			phone: "+244 923 456 960",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_023",
			name: "Prof. Cláudia Sardinha",
			email: "claudia.sardinha@uan.edu.ao",
			phone: "+244 923 456 961",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_024",
			name: "Dr. Alexandre Monteiro",
			email: "alexandre.monteiro@efitel.co.ao",
			phone: "+244 923 456 962",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_025",
			name: "Eng. Sérgio Meireles",
			email: "sergio.meireles@refriango.co.ao",
			phone: "+244 923 456 963",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_026",
			name: "Dra. Mónica Vieira",
			email: "monica.vieira@sonangol.co.ao",
			phone: "+244 923 456 964",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_027",
			name: "Eng. Fábio Ramos",
			email: "fabio.ramos@taag.co.ao",
			phone: "+244 923 456 965",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_028",
			name: "Prof. Ricardo Santos",
			email: "ricardo.santos@iscp.co.ao",
			phone: "+244 923 456 966",
			group: "Academia",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_029",
			name: "Dr. Anália Chichava",
			email: "analia.chichava@bfa.co.ao",
			phone: "+244 923 456 967",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_030",
			name: "Eng. Vasco Fernandes",
			email: "vasco.fernandes@angolaseg.co.ao",
			phone: "+244 923 456 968",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_031",
			name: "Dra. Patrícia Chaves",
			email: "patricia.chaves@unitel.co.ao",
			phone: "+244 923 456 969",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_032",
			name: "Eng. Nélson Tomás",
			email: "nelson.tomas@bp.co.ao",
			phone: "+244 923 456 970",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_033",
			name: "Prof. Beatriz Gomes",
			email: "beatriz.gomes@uan.edu.ao",
			phone: "+244 923 456 971",
			group: "Academia",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_034",
			name: "Dr. Carlos Kulemba",
			email: "carlos.kulemba@sonangol.co.ao",
			phone: "+244 923 456 972",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_035",
			name: "Eng. Sara Caetano",
			email: "sara.caetano@taag.co.ao",
			phone: "+244 923 456 973",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_036",
			name: "Dra. Nádia Sampalo",
			email: "nadia.sampalo@bci.co.ao",
			phone: "+244 923 456 974",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_037",
			name: "Eng. Eduardo Gaspar",
			email: "eduardo.gaspar@refriango.co.ao",
			phone: "+244 923 456 975",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_038",
			name: "Prof. Ana Coelho",
			email: "ana.coelho@iscp.co.ao",
			phone: "+244 923 456 976",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_039",
			name: "Dr. Rui Marques",
			email: "rui.marques@angolamining.co.ao",
			phone: "+244 923 456 977",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_040",
			name: "Eng. Tânia Malheiro",
			email: "tania.malheiro@efitel.co.ao",
			phone: "+244 923 456 978",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_041",
			name: "Dra. Susana Manuel",
			email: "susana.manuel@unitel.co.ao",
			phone: "+244 923 456 979",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_042",
			name: "Eng. Marcos Pires",
			email: "marcos.pires@bfa.co.ao",
			phone: "+244 923 456 980",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_043",
			name: "Prof. Clara Carneiro",
			email: "clara.carneiro@uan.edu.ao",
			phone: "+244 923 456 981",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_044",
			name: "Dr. Sérgio Mendonça",
			email: "sergio.mendonca@bp.co.ao",
			phone: "+244 923 456 982",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_045",
			name: "Eng. Raquel Brito",
			email: "raquel.brito@sonangol.co.ao",
			phone: "+244 923 456 983",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_046",
			name: "Dra. Marta Canata",
			email: "marta.canata@taag.co.ao",
			phone: "+244 923 456 984",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_047",
			name: "Eng. Paulo Palheta",
			email: "paulo.palheta@angolaseg.co.ao",
			phone: "+244 923 456 985",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_048",
			name: "Prof. Luís Pedro",
			email: "luis.pedro@iscp.co.ao",
			phone: "+244 923 456 986",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_049",
			name: "Dr. Ana Maria",
			email: "ana.maria@bci.co.ao",
			phone: "+244 923 456 987",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_050",
			name: "Eng. Tiago Pires",
			email: "tiago.pires@refriango.co.ao",
			phone: "+244 923 456 988",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_051",
			name: "Dra. Cristina Luis",
			email: "cristina.luis@efitel.co.ao",
			phone: "+244 923 456 989",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_052",
			name: "Eng. Nelson Semedo",
			email: "nelson.semedo@unitel.co.ao",
			phone: "+244 923 456 990",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_053",
			name: "Prof. Sara Cancela",
			email: "sara.cancela@uan.edu.ao",
			phone: "+244 923 456 991",
			group: "Academia",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_054",
			name: "Dr. António Ganhão",
			email: "antonio.ganhao@bp.co.ao",
			phone: "+244 923 456 992",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_055",
			name: "Eng. Helena Vale",
			email: "helena.vale@sonangol.co.ao",
			phone: "+244 923 456 993",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_056",
			name: "Dra. Liliana Chaves",
			email: "liliana.chaves@taag.co.ao",
			phone: "+244 923 456 994",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_057",
			name: "Eng. Rui Gomes",
			email: "rui.gomes@angolamining.co.ao",
			phone: "+244 923 456 995",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_058",
			name: "Prof. Teresa Lopes",
			email: "teresa.lopes@iscp.co.ao",
			phone: "+244 923 456 996",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_059",
			name: "Dr. Carlos Menezes",
			email: "carlos.menezes@bfa.co.ao",
			phone: "+244 923 456 997",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_060",
			name: "Eng. Mónica Tavares",
			email: "monica.tavares@angolaseg.co.ao",
			phone: "+244 923 456 998",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_061",
			name: "Dra. Patrícia Fraga",
			email: "patricia.fraga@bci.co.ao",
			phone: "+244 923 456 999",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_062",
			name: "Eng. Diogo Nascimento",
			email: "diogo.nascimento@refriango.co.ao",
			phone: "+244 923 457 000",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_063",
			name: "Prof. Carla Ribeiro",
			email: "carla.ribeiro@uan.edu.ao",
			phone: "+244 923 457 001",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_064",
			name: "Dr. Sérgio Figueiredo",
			email: "sergio.figueiredo@efitel.co.ao",
			phone: "+244 923 457 002",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_065",
			name: "Eng. Cristina Gaspar",
			email: "cristina.gaspar@unitel.co.ao",
			phone: "+244 923 457 003",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_066",
			name: "Dra. Alexandra Pires",
			email: "alexandra.pires@sonangol.co.ao",
			phone: "+244 923 457 004",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_067",
			name: "Eng. Rui Tomás",
			email: "rui.tomas@bp.co.ao",
			phone: "+244 923 457 005",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_068",
			name: "Prof. Marta Simões",
			email: "marta.simoes@iscp.co.ao",
			phone: "+244 923 457 006",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_069",
			name: "Dr. Ricardo Braga",
			email: "ricardo.braga@taag.co.ao",
			phone: "+244 923 457 007",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_070",
			name: "Eng. Ana Mendes",
			email: "ana.mendes@angolaseg.co.ao",
			phone: "+244 923 457 008",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_071",
			name: "Dra. Célia Baptista",
			email: "celia.baptista@bfa.co.ao",
			phone: "+244 923 457 009",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_072",
			name: "Eng. Marcos Santos",
			email: "marcos.santos@bci.co.ao",
			phone: "+244 923 457 010",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_073",
			name: "Prof. Vanessa Lopes",
			email: "vanessa.lopes@uan.edu.ao",
			phone: "+244 923 457 011",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_074",
			name: "Dr. Nuno Reis",
			email: "nuno.reis@refriango.co.ao",
			phone: "+244 923 457 012",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_075",
			name: "Eng. Raquel Marques",
			email: "raquel.marques@efitel.co.ao",
			phone: "+244 923 457 013",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_076",
			name: "Dra. Sara Vieira",
			email: "sara.vieira@unitel.co.ao",
			phone: "+244 923 457 014",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_077",
			name: "Eng. Pedro Monteiro",
			email: "pedro.monteiro@sonangol.co.ao",
			phone: "+244 923 457 015",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_078",
			name: "Prof. Helena Coelho",
			email: "helena.coelho@iscp.co.ao",
			phone: "+244 923 457 016",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_079",
			name: "Dr. Fábio Almeida",
			email: "fabio.almeida@bp.co.ao",
			phone: "+244 923 457 017",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_080",
			name: "Eng. Marta Dias",
			email: "marta.dias@taag.co.ao",
			phone: "+244 923 457 018",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_081",
			name: "Dra. Cristina Ferreira",
			email: "cristina.ferreira@angolamining.co.ao",
			phone: "+244 923 457 019",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_082",
			name: "Eng. Luís Cardoso",
			email: "luis.cardoso@angolaseg.co.ao",
			phone: "+244 923 457 020",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_083",
			name: "Prof. Ana Rodrigues",
			email: "ana.rodrigues@uan.edu.ao",
			phone: "+244 923 457 021",
			group: "Academia",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_084",
			name: "Dr. Pedro Guerra",
			email: "pedro.guerra@bfa.co.ao",
			phone: "+244 923 457 022",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_085",
			name: "Eng. Sónia Rodrigues",
			email: "sonia.rodrigues@bci.co.ao",
			phone: "+244 923 457 023",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_086",
			name: "Dra. Teresa Gaspar",
			email: "teresa.gaspar@efitel.co.ao",
			phone: "+244 923 457 024",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_087",
			name: "Eng. Nelson Pinto",
			email: "nelson.pinto@refriango.co.ao",
			phone: "+244 923 457 025",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_088",
			name: "Prof. Beatriz Lando",
			email: "beatriz.lando@iscp.co.ao",
			phone: "+244 923 457 026",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_089",
			name: "Dr. Rui Tavares",
			email: "rui.tavares@unitel.co.ao",
			phone: "+244 923 457 027",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_090",
			name: "Eng. Sara Pires",
			email: "sara.pires@sonangol.co.ao",
			phone: "+244 923 457 028",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_091",
			name: "Dra. Mónica Barros",
			email: "monica.barros@taag.co.ao",
			phone: "+244 923 457 029",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_092",
			name: "Eng. Carlos Neto",
			email: "carlos.neto@bp.co.ao",
			phone: "+244 923 457 030",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_093",
			name: "Prof. Patrícia Sardinha",
			email: "patricia.sardinha@uan.edu.ao",
			phone: "+244 923 457 031",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_094",
			name: "Dr. Diogo Mendes",
			email: "diogo.mendes@angolamining.co.ao",
			phone: "+244 923 457 032",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_095",
			name: "Eng. Catarina Santos",
			email: "catarina.santos@angolaseg.co.ao",
			phone: "+244 923 457 033",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_096",
			name: "Dra. Alexandra Ribeiro",
			email: "alexandra.ribeiro@bfa.co.ao",
			phone: "+244 923 457 034",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_097",
			name: "Eng. Paulo Vieira",
			email: "paulo.vieira@bci.co.ao",
			phone: "+244 923 457 035",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_098",
			name: "Prof. Luísa Mendonça",
			email: "luisa.mendonca@iscp.co.ao",
			phone: "+244 923 457 036",
			group: "Academia",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_099",
			name: "Dr. Sérgio Lopes",
			email: "sergio.lopes@efitel.co.ao",
			phone: "+244 923 457 037",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_100",
			name: "Eng. Raquel Tavares",
			email: "raquel.tavares@refriango.co.ao",
			phone: "+244 923 457 038",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_101",
			name: "Dra. Marta Caneta",
			email: "marta.caneta@unitel.co.ao",
			phone: "+244 923 457 039",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_102",
			name: "Eng. Nuno Carvalho",
			email: "nuno.carvalho@sonangol.co.ao",
			phone: "+244 923 457 040",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_103",
			name: "Prof. Cristina Pinto",
			email: "cristina.pinto@uan.edu.ao",
			phone: "+244 923 457 041",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_104",
			name: "Dr. Marcos Braga",
			email: "marcos.braga@taag.co.ao",
			phone: "+244 923 457 042",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_105",
			name: "Eng. Sara Gaspar",
			email: "sara.gaspar@bp.co.ao",
			phone: "+244 923 457 043",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_106",
			name: "Dra. Ana Almeida",
			email: "ana.almeida@angolamining.co.ao",
			phone: "+244 923 457 044",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_107",
			name: "Eng. Ricardo Cardoso",
			email: "ricardo.cardoso@angolaseg.co.ao",
			phone: "+244 923 457 045",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_108",
			name: "Prof. Mónica Dias",
			email: "monica.dias@iscp.co.ao",
			phone: "+244 923 457 046",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_109",
			name: "Dr. Pedro Marques",
			email: "pedro.marques@bfa.co.ao",
			phone: "+244 923 457 047",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_110",
			name: "Eng. Célia Reis",
			email: "celia.reis@bci.co.ao",
			phone: "+244 923 457 048",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_111",
			name: "Dra. Teresa Marques",
			email: "teresa.marques@efitel.co.ao",
			phone: "+244 923 457 049",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_112",
			name: "Eng. Sérgio Monteiro",
			email: "sergio.monteiro@refriango.co.ao",
			phone: "+244 923 457 050",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_113",
			name: "Prof. Patrícia Neto",
			email: "patricia.neto@uan.edu.ao",
			phone: "+244 923 457 051",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_114",
			name: "Dr. Luís Rodrigues",
			email: "luis.rodrigues@unitel.co.ao",
			phone: "+244 923 457 052",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_115",
			name: "Eng. Raquel Vieira",
			email: "raquel.vieira@sonangol.co.ao",
			phone: "+244 923 457 053",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_116",
			name: "Dra. Sara Lopes",
			email: "sara.lopes@taag.co.ao",
			phone: "+244 923 457 054",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_117",
			name: "Eng. Paulo Barros",
			email: "paulo.barros@bp.co.ao",
			phone: "+244 923 457 055",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_118",
			name: "Prof. Ana Tavares",
			email: "ana.tavares@iscp.co.ao",
			phone: "+244 923 457 056",
			group: "Academia",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_119",
			name: "Dr. Rui Gaspar",
			email: "rui.gaspar@angolamining.co.ao",
			phone: "+244 923 457 057",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_120",
			name: "Eng. Helena Pinto",
			email: "helena.pinto@angolaseg.co.ao",
			phone: "+244 923 457 058",
			group: "Participantes",
			type: "COLLEAGUE",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		// FRIENDS (15)
		{
			id: "gst_con_121",
			name: "André Kapinga",
			email: "andre.kapinga@gmail.com",
			phone: "+244 923 457 059",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_122",
			name: "Teresa Kapinga",
			email: "teresa.kapinga@gmail.com",
			phone: "+244 923 457 060",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_123",
			name: "Marcos Calei",
			email: "marcos.calei@outlook.com",
			phone: "+244 923 457 061",
			group: "Conhecidos",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_124",
			name: "Ana Kassange",
			email: "ana.kassange@gmail.com",
			phone: "+244 923 457 062",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_125",
			name: "Nelson Cambuta",
			email: "nelson.cambuta@outlook.com",
			phone: "+244 923 457 063",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_126",
			name: "Sofia Sementeiro",
			email: "sofia.sementeiro@gmail.com",
			phone: "+244 923 457 064",
			group: "Conhecidos",
			type: "FRIEND",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_127",
			name: "Pedro Dembo",
			email: "pedro.dembo@gmail.com",
			phone: "+244 923 457 065",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_128",
			name: "Raquel Lussaty",
			email: "raquel.lussaty@outlook.com",
			phone: "+244 923 457 066",
			group: "Conhecidos",
			type: "FRIEND",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_129",
			name: "Fábio Missionais",
			email: "fabio.missionais@gmail.com",
			phone: "+244 923 457 067",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_130",
			name: "Catarina Bumba",
			email: "catarina.bumba@gmail.com",
			phone: "+244 923 457 068",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_131",
			name: "Ricardo Quaresma",
			email: "ricardo.quaresma@outlook.com",
			phone: "+244 923 457 069",
			group: "Conhecidos",
			type: "FRIEND",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_132",
			name: "Mariana Kunga",
			email: "mariana.kunga@gmail.com",
			phone: "+244 923 457 070",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_133",
			name: "Diogo Chipaco",
			email: "diogo.chipaco@gmail.com",
			phone: "+244 923 457 071",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_134",
			name: "Letícia Mabululu",
			email: "leticia.mabululu@outlook.com",
			phone: "+244 923 457 072",
			group: "Conhecidos",
			type: "FRIEND",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_135",
			name: "Tomás Mocuibe",
			email: "tomas.mocuibe@gmail.com",
			phone: "+244 923 457 073",
			group: "Conhecidos",
			type: "FRIEND",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		// VIP (5)
		{
			id: "gst_con_136",
			name: "Dr. Manuel Ribeiro",
			email: "manuel.ribeiro@sonangol.co.ao",
			phone: "+244 923 457 074",
			group: "Convidados VIP",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_137",
			name: "Eng. Sónia Tomás",
			email: "sonia.tomas@unitel.co.ao",
			phone: "+244 923 457 075",
			group: "Convidados VIP",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_138",
			name: "Prof. Carlos Matos",
			email: "carlos.matos@ucan.co.ao",
			phone: "+244 923 457 076",
			group: "Convidados VIP",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_139",
			name: "Dra. Teresa Marques",
			email: "teresa.marques@angolaseg.co.ao",
			phone: "+244 923 457 077",
			group: "Convidados VIP",
			type: "VIP",
			status: "DECLINED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_140",
			name: "Eng. Nelson Tomás",
			email: "nelson.tomas@bp.co.ao",
			phone: "+244 923 457 078",
			group: "Convidados VIP",
			type: "VIP",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		// OTHER (10)
		{
			id: "gst_con_141",
			name: "Fernanda Macuácua",
			email: "fernanda.macuacua@outlook.com",
			phone: "+244 923 457 079",
			group: "Outros",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_142",
			name: "Ricardo Bandeira",
			email: "ricardo.bandeira@gmail.com",
			phone: "+244 923 457 080",
			group: "Outros",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_143",
			name: "Sara Zacarias",
			email: "sara.zacarias@outlook.com",
			phone: "+244 923 457 081",
			group: "Outros",
			type: "OTHER",
			status: "PENDING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_144",
			name: "Paulo Nguenca",
			email: "paulo.nguenca@gmail.com",
			phone: "+244 923 457 082",
			group: "Outros",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_145",
			name: "Helena Sementeiro",
			email: "helena.sementeiro@outlook.com",
			phone: "+244 923 457 083",
			group: "Outros",
			type: "OTHER",
			status: "WAITING",
			companionsLimit: 0,
		},
		{
			id: "gst_con_146",
			name: "Nuno Casimiro",
			email: "nuno.casimiro@gmail.com",
			phone: "+244 923 457 084",
			group: "Outros",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_147",
			name: "Marta Kassange",
			email: "marta.kassange@outlook.com",
			phone: "+244 923 457 085",
			group: "Outros",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_148",
			name: "Diogo Pires",
			email: "diogo.pires@gmail.com",
			phone: "+244 923 457 086",
			group: "Outros",
			type: "OTHER",
			status: "MAYBE",
			companionsLimit: 0,
		},
		{
			id: "gst_con_149",
			name: "Célia Candundo",
			email: "celia.candundo@outlook.com",
			phone: "+244 923 457 087",
			group: "Outros",
			type: "OTHER",
			status: "CONFIRMED",
			companionsLimit: 0,
		},
		{
			id: "gst_con_150",
			name: "Rui Mabululu",
			email: "rui.mabululu@gmail.com",
			phone: "+244 923 457 088",
			group: "Outros",
			type: "OTHER",
			status: "DECLINED",
			companionsLimit: 0,
		},
	];
}
