import {
	daysAgo,
	daysAhead,
	EVENTS,
	eventDateTime,
	monthsAgo,
	monthsAhead,
	prisma,
} from "./helpers";

export async function seedSchedules() {
	const weddingDate = monthsAhead(4);
	const engagementDate = monthsAhead(1);
	const birthdayDate = new Date();
	const conferenceDate = monthsAgo(2);
	const corporateDate = daysAhead(14);
	const workshopDate = daysAhead(21);
	const babyShowerDate = monthsAgo(1);
	const ceremonyDate = monthsAhead(5);

	await prisma.schedule.deleteMany();

	const schedules = [
		// ── WEDDING ───────────────────────────────────────────────
		{
			id: "sch_wed_001",
			eventId: EVENTS.WEDDING,
			title: "Montagem da decoração",
			description: null,
			startAt: eventDateTime(weddingDate, 9, 0),
			endAt: eventDateTime(weddingDate, 13, 0),
			location: "Convento de São Francisco",
			responsible: "Equipe de montagem",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_002",
			eventId: EVENTS.WEDDING,
			title: "Ensaio da cerimónia",
			description: null,
			startAt: eventDateTime(weddingDate, 13, 0),
			endAt: eventDateTime(weddingDate, 14, 0),
			location: "Capela do Convento",
			responsible: "Coordenador",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_003",
			eventId: EVENTS.WEDDING,
			title: "Preparação da noiva",
			description: null,
			startAt: eventDateTime(weddingDate, 14, 0),
			endAt: eventDateTime(weddingDate, 15, 0),
			location: "Sala de preparação",
			responsible: "Beleza Noiva",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_004",
			eventId: EVENTS.WEDDING,
			title: "Cerimónia religiosa",
			description: null,
			startAt: eventDateTime(weddingDate, 15, 0),
			endAt: eventDateTime(weddingDate, 16, 0),
			location: "Capela do Convento",
			responsible: "Padre celebrante",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_005",
			eventId: EVENTS.WEDDING,
			title: "Sessão fotográfica",
			description: null,
			startAt: eventDateTime(weddingDate, 16, 0),
			endAt: eventDateTime(weddingDate, 17, 0),
			location: "Jardim do Convento",
			responsible: "Olhar Fotográfico",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_006",
			eventId: EVENTS.WEDDING,
			title: "Recepção — Cocktail",
			description: null,
			startAt: eventDateTime(weddingDate, 17, 0),
			endAt: eventDateTime(weddingDate, 18, 0),
			location: "Salão Principal",
			responsible: "Chef Ngola",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_007",
			eventId: EVENTS.WEDDING,
			title: "Jantar",
			description: null,
			startAt: eventDateTime(weddingDate, 18, 0),
			endAt: eventDateTime(weddingDate, 20, 0),
			location: "Salão Principal",
			responsible: "Chef Ngola",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_008",
			eventId: EVENTS.WEDDING,
			title: "Corte do bolo",
			description: null,
			startAt: eventDateTime(weddingDate, 20, 0),
			endAt: eventDateTime(weddingDate, 20, 30),
			location: "Salão Principal",
			responsible: "Coordenador",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_009",
			eventId: EVENTS.WEDDING,
			title: "Pista de dança",
			description: null,
			startAt: eventDateTime(weddingDate, 20, 30),
			endAt: eventDateTime(weddingDate, 25, 30),
			location: "Pista de Dança",
			responsible: "Som & Arte",
			status: "PENDING" as const,
		},
		{
			id: "sch_wed_010",
			eventId: EVENTS.WEDDING,
			title: "Fogos de artifício",
			description: null,
			startAt: eventDateTime(weddingDate, 25, 30),
			endAt: eventDateTime(weddingDate, 25, 45),
			location: "Jardim",
			responsible: "Equipe técnica",
			status: "PENDING" as const,
		},

		// ── ENGAGEMENT ────────────────────────────────────────────
		{
			id: "sch_eng_001",
			eventId: EVENTS.ENGAGEMENT,
			title: "Montagem do espaço",
			description: null,
			startAt: eventDateTime(engagementDate, 15, 0),
			endAt: eventDateTime(engagementDate, 17, 30),
			location: "Clube Mineiro",
			responsible: "Equipe de montagem",
			status: "PENDING" as const,
		},
		{
			id: "sch_eng_002",
			eventId: EVENTS.ENGAGEMENT,
			title: "Recepção dos convidados",
			description: null,
			startAt: eventDateTime(engagementDate, 18, 0),
			endAt: eventDateTime(engagementDate, 19, 0),
			location: "Jardim do Clube",
			responsible: "Coordenador",
			status: "PENDING" as const,
		},
		{
			id: "sch_eng_003",
			eventId: EVENTS.ENGAGEMENT,
			title: "Discurso do noivo",
			description: null,
			startAt: eventDateTime(engagementDate, 19, 0),
			endAt: eventDateTime(engagementDate, 19, 30),
			location: "Palco",
			responsible: "David",
			status: "PENDING" as const,
		},
		{
			id: "sch_eng_004",
			eventId: EVENTS.ENGAGEMENT,
			title: "Corte do bolo",
			description: null,
			startAt: eventDateTime(engagementDate, 19, 30),
			endAt: eventDateTime(engagementDate, 20, 0),
			location: "Mesa principal",
			responsible: "Coordenador",
			status: "PENDING" as const,
		},
		{
			id: "sch_eng_005",
			eventId: EVENTS.ENGAGEMENT,
			title: "Festa e dança",
			description: null,
			startAt: eventDateTime(engagementDate, 20, 0),
			endAt: eventDateTime(engagementDate, 23, 0),
			location: "Pista de dança",
			responsible: "DJ",
			status: "PENDING" as const,
		},

		// ── BIRTHDAY ──────────────────────────────────────────────
		{
			id: "sch_bth_001",
			eventId: EVENTS.BIRTHDAY,
			title: "Preparação do espaço",
			description: null,
			startAt: eventDateTime(birthdayDate, 16, 0),
			endAt: eventDateTime(birthdayDate, 18, 0),
			location: "Restaurante O Cantinho",
			responsible: "Anfitrião",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_bth_002",
			eventId: EVENTS.BIRTHDAY,
			title: "Decoração",
			description: null,
			startAt: eventDateTime(birthdayDate, 17, 0),
			endAt: eventDateTime(birthdayDate, 18, 30),
			location: "Salão principal",
			responsible: "Equipe",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_bth_003",
			eventId: EVENTS.BIRTHDAY,
			title: "Recepção dos convidados",
			description: null,
			startAt: eventDateTime(birthdayDate, 18, 30),
			endAt: eventDateTime(birthdayDate, 19, 30),
			location: "Entrada",
			responsible: "Anfitrião",
			status: "IN_PROGRESS" as const,
		},
		{
			id: "sch_bth_004",
			eventId: EVENTS.BIRTHDAY,
			title: "Jantar",
			description: null,
			startAt: eventDateTime(birthdayDate, 19, 30),
			endAt: eventDateTime(birthdayDate, 21, 0),
			location: "Salão principal",
			responsible: "Restaurante",
			status: "PENDING" as const,
		},
		{
			id: "sch_bth_005",
			eventId: EVENTS.BIRTHDAY,
			title: "Surpresa e bolo",
			description: null,
			startAt: eventDateTime(birthdayDate, 21, 0),
			endAt: eventDateTime(birthdayDate, 21, 30),
			location: "Salão principal",
			responsible: "Organizador",
			status: "PENDING" as const,
		},
		{
			id: "sch_bth_006",
			eventId: EVENTS.BIRTHDAY,
			title: "Festa e DJ",
			description: null,
			startAt: eventDateTime(birthdayDate, 21, 30),
			endAt: eventDateTime(birthdayDate, 25, 0),
			location: "Pista de dança",
			responsible: "DJ",
			status: "PENDING" as const,
		},

		// ── CONFERENCE ────────────────────────────────────────────
		{
			id: "sch_con_001",
			eventId: EVENTS.CONFERENCE,
			title: "Registo e credenciação",
			description: null,
			startAt: eventDateTime(conferenceDate, 8, 0),
			endAt: eventDateTime(conferenceDate, 9, 0),
			location: "Entrada",
			responsible: "Equipe",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_002",
			eventId: EVENTS.CONFERENCE,
			title: "Cerimónia de abertura",
			description: null,
			startAt: eventDateTime(conferenceDate, 9, 0),
			endAt: eventDateTime(conferenceDate, 9, 30),
			location: "Auditório principal",
			responsible: "Diretor",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_003",
			eventId: EVENTS.CONFERENCE,
			title: "Keynote: IA em Angola",
			description: null,
			startAt: eventDateTime(conferenceDate, 9, 30),
			endAt: eventDateTime(conferenceDate, 10, 30),
			location: "Auditório principal",
			responsible: "Dr. Silva",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_004",
			eventId: EVENTS.CONFERENCE,
			title: "Coffee break",
			description: null,
			startAt: eventDateTime(conferenceDate, 10, 30),
			endAt: eventDateTime(conferenceDate, 11, 0),
			location: "Área de exposição",
			responsible: "Catering",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_005",
			eventId: EVENTS.CONFERENCE,
			title: "Workshops paralelos",
			description: null,
			startAt: eventDateTime(conferenceDate, 11, 0),
			endAt: eventDateTime(conferenceDate, 13, 0),
			location: "Salas 1-3",
			responsible: "Facilitadores",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_006",
			eventId: EVENTS.CONFERENCE,
			title: "Almoço",
			description: null,
			startAt: eventDateTime(conferenceDate, 13, 0),
			endAt: eventDateTime(conferenceDate, 14, 0),
			location: "Restaurante",
			responsible: "Catering",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_007",
			eventId: EVENTS.CONFERENCE,
			title: "Painel de debate",
			description: null,
			startAt: eventDateTime(conferenceDate, 14, 0),
			endAt: eventDateTime(conferenceDate, 16, 0),
			location: "Auditório principal",
			responsible: "Modador",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_con_008",
			eventId: EVENTS.CONFERENCE,
			title: "Encerramento e certificados",
			description: null,
			startAt: eventDateTime(conferenceDate, 16, 0),
			endAt: eventDateTime(conferenceDate, 17, 0),
			location: "Auditório principal",
			responsible: "Diretor",
			status: "COMPLETED" as const,
		},

		// ── CORPORATE ─────────────────────────────────────────────
		{
			id: "sch_cor_001",
			eventId: EVENTS.CORPORATE,
			title: "Montagem do espaço",
			description: null,
			startAt: eventDateTime(corporateDate, 17, 0),
			endAt: eventDateTime(corporateDate, 19, 0),
			location: "Hotel Epic Sana",
			responsible: "Equipe",
			status: "PENDING" as const,
		},
		{
			id: "sch_cor_002",
			eventId: EVENTS.CORPORATE,
			title: "Welcome drink",
			description: null,
			startAt: eventDateTime(corporateDate, 19, 30),
			endAt: eventDateTime(corporateDate, 20, 0),
			location: "Lobby",
			responsible: "Rececionista",
			status: "PENDING" as const,
		},
		{
			id: "sch_cor_003",
			eventId: EVENTS.CORPORATE,
			title: "Jantar e discursos",
			description: null,
			startAt: eventDateTime(corporateDate, 20, 0),
			endAt: eventDateTime(corporateDate, 22, 0),
			location: "Salão de banquetes",
			responsible: "Diretor",
			status: "PENDING" as const,
		},
		{
			id: "sch_cor_004",
			eventId: EVENTS.CORPORATE,
			title: "Música e convívio",
			description: null,
			startAt: eventDateTime(corporateDate, 22, 0),
			endAt: eventDateTime(corporateDate, 23, 0),
			location: "Bar",
			responsible: "DJ",
			status: "PENDING" as const,
		},
		{
			id: "sch_cor_005",
			eventId: EVENTS.CORPORATE,
			title: "Encerramento",
			description: null,
			startAt: eventDateTime(corporateDate, 23, 0),
			endAt: eventDateTime(corporateDate, 23, 30),
			location: "Lobby",
			responsible: "Rececionista",
			status: "PENDING" as const,
		},

		// ── WORKSHOP ──────────────────────────────────────────────
		{
			id: "sch_wor_001",
			eventId: EVENTS.WORKSHOP,
			title: "Recepção e café",
			description: null,
			startAt: eventDateTime(workshopDate, 8, 30),
			endAt: eventDateTime(workshopDate, 9, 0),
			location: "Hub de Criatividade",
			responsible: "Organizador",
			status: "PENDING" as const,
		},
		{
			id: "sch_wor_002",
			eventId: EVENTS.WORKSHOP,
			title: "Sessão 1: Design Thinking",
			description: null,
			startAt: eventDateTime(workshopDate, 9, 0),
			endAt: eventDateTime(workshopDate, 12, 0),
			location: "Sala principal",
			responsible: "Instrutor",
			status: "PENDING" as const,
		},
		{
			id: "sch_wor_003",
			eventId: EVENTS.WORKSHOP,
			title: "Almoço",
			description: null,
			startAt: eventDateTime(workshopDate, 12, 0),
			endAt: eventDateTime(workshopDate, 13, 0),
			location: "Copa",
			responsible: "Catering",
			status: "PENDING" as const,
		},
		{
			id: "sch_wor_004",
			eventId: EVENTS.WORKSHOP,
			title: "Sessão 2: Prática criativa",
			description: null,
			startAt: eventDateTime(workshopDate, 13, 0),
			endAt: eventDateTime(workshopDate, 17, 0),
			location: "Sala principal",
			responsible: "Instrutor",
			status: "PENDING" as const,
		},

		// ── BABY SHOWER ───────────────────────────────────────────
		{
			id: "sch_bab_001",
			eventId: EVENTS.BABY_SHOWER,
			title: "Montagem da decoração",
			description: null,
			startAt: eventDateTime(babyShowerDate, 13, 0),
			endAt: eventDateTime(babyShowerDate, 15, 0),
			location: "Jardim da Tia Graça",
			responsible: "Equipe",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_bab_002",
			eventId: EVENTS.BABY_SHOWER,
			title: "Recepção e brindes",
			description: null,
			startAt: eventDateTime(babyShowerDate, 15, 0),
			endAt: eventDateTime(babyShowerDate, 16, 0),
			location: "Jardim",
			responsible: "Anfitriã",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_bab_003",
			eventId: EVENTS.BABY_SHOWER,
			title: "Jogos e brincadeiras",
			description: null,
			startAt: eventDateTime(babyShowerDate, 16, 0),
			endAt: eventDateTime(babyShowerDate, 18, 0),
			location: "Jardim",
			responsible: "Animadora",
			status: "COMPLETED" as const,
		},
		{
			id: "sch_bab_004",
			eventId: EVENTS.BABY_SHOWER,
			title: "Corte do bolo e lembranças",
			description: null,
			startAt: eventDateTime(babyShowerDate, 18, 0),
			endAt: eventDateTime(babyShowerDate, 20, 0),
			location: "Jardim",
			responsible: "Anfitriã",
			status: "COMPLETED" as const,
		},

		// ── CEREMONY ──────────────────────────────────────────────
		{
			id: "sch_cer_001",
			eventId: EVENTS.CEREMONY,
			title: "Montagem da igreja",
			description: null,
			startAt: eventDateTime(ceremonyDate, 7, 0),
			endAt: eventDateTime(ceremonyDate, 8, 30),
			location: "Igreja de São Pedro",
			responsible: "Equipe de decoração",
			status: "PENDING" as const,
		},
		{
			id: "sch_cer_002",
			eventId: EVENTS.CEREMONY,
			title: "Recepção dos convidados",
			description: null,
			startAt: eventDateTime(ceremonyDate, 8, 30),
			endAt: eventDateTime(ceremonyDate, 9, 0),
			location: "Entrada da igreja",
			responsible: "Equipe",
			status: "PENDING" as const,
		},
		{
			id: "sch_cer_003",
			eventId: EVENTS.CEREMONY,
			title: "Cerimónia religiosa",
			description: null,
			startAt: eventDateTime(ceremonyDate, 9, 0),
			endAt: eventDateTime(ceremonyDate, 11, 0),
			location: "Nave da igreja",
			responsible: "Padre",
			status: "PENDING" as const,
		},
		{
			id: "sch_cer_004",
			eventId: EVENTS.CEREMONY,
			title: "Sessão fotográfica",
			description: null,
			startAt: eventDateTime(ceremonyDate, 11, 0),
			endAt: eventDateTime(ceremonyDate, 11, 30),
			location: "Pátio da igreja",
			responsible: "Fotógrafo",
			status: "PENDING" as const,
		},
		{
			id: "sch_cer_005",
			eventId: EVENTS.CEREMONY,
			title: "Recepção no salão",
			description: null,
			startAt: eventDateTime(ceremonyDate, 11, 30),
			endAt: eventDateTime(ceremonyDate, 12, 30),
			location: "Salão paroquial",
			responsible: "Coordenador",
			status: "PENDING" as const,
		},
		{
			id: "sch_cer_006",
			eventId: EVENTS.CEREMONY,
			title: "Almoço de recepção",
			description: null,
			startAt: eventDateTime(ceremonyDate, 12, 30),
			endAt: eventDateTime(ceremonyDate, 13, 30),
			location: "Salão paroquial",
			responsible: "Catering",
			status: "PENDING" as const,
		},
	];

	await prisma.schedule.createMany({ data: schedules });

	return schedules.length;
}
