import { prisma, EVENTS, daysAgo, daysAhead, monthsAhead } from "./helpers";

export async function seedVendors() {
	// ── Vendors ────────────────────────────────────────────────────────
	const vendors = [
		// ── EVENTS.WEDDING (8 vendors) ──────────────────────────────────
		{
			id: "vnd_wedding_001",
			eventId: EVENTS.WEDDING,
			name: "Jardim das Flores — Decoração",
			category: "DECORATION" as const,
			phone: "+244 923 456 789",
			email: "contato@jardimdasflores.ao",
			address: "Rua da Resistência, Luanda",
			status: "CONTRACTED" as const,
			description: "Empresa especializada em decoração floral e ambientação para casamentos.",
			notes: "Contrato assinado — tema botânico aprovado.",
			createdAt: daysAgo(60),
		},
		{
			id: "vnd_wedding_002",
			eventId: EVENTS.WEDDING,
			name: "Chef Ngola — Catering",
			category: "CATERING" as const,
			phone: "+244 912 345 678",
			email: "reservas@chefngola.ao",
			address: "Rua Comandante Gika, Luanda",
			status: "CONTRACTED" as const,
			description: "Chef renomado com experiência em catering para grandes eventos.",
			notes: "Menu angolano tradicional e internacional aprovado.",
			createdAt: daysAgo(55),
		},
		{
			id: "vnd_wedding_003",
			eventId: EVENTS.WEDDING,
			name: "Som & Arte — DJ e Banda",
			category: "MUSIC" as const,
			phone: "+244 934 567 890",
			email: "bookings@somarte.ao",
			address: "Rua dos Enganos, Luanda",
			status: "NEGOTIATING" as const,
			description: "DJ e banda ao vivo para eventos — repertório variado.",
			notes: "Proposta enviada — aguardando confirmação de valores.",
			createdAt: daysAgo(45),
		},
		{
			id: "vnd_wedding_004",
			eventId: EVENTS.WEDDING,
			name: "Olhar Fotográfico",
			category: "PHOTOGRAPHY" as const,
			phone: "+244 945 678 901",
			email: "info@olharfotografico.ao",
			address: "Rua Major Kanhangulo, Luanda",
			status: "CONTRACTED" as const,
			description: "Estúdio fotográfico com foco em casamentos e eventos especiais.",
			notes: "Pacote completo: fotos + vídeo + drone.",
			createdAt: daysAgo(50),
		},
		{
			id: "vnd_wedding_005",
			eventId: EVENTS.WEDDING,
			name: "Belleza Noiva — Beleza",
			category: "BEAUTY" as const,
			phone: "+244 956 789 012",
			email: "agendamentos@bellanoiva.ao",
			address: "Rua 5 de Outubro, Luanda",
			status: "CONTACTED" as const,
			description: "Salão de beleza especializado em noivas — maquiagem, penteados e tratamentos.",
			notes: "Contactada — aguardando resposta.",
			createdAt: daysAgo(30),
		},
		{
			id: "vnd_wedding_006",
			eventId: EVENTS.WEDDING,
			name: "Transportes Reais",
			category: "TRANSPORT" as const,
			phone: "+244 967 890 123",
			email: "info@transportesreais.ao",
			address: "Estrada de Catete, Luanda",
			status: "PROSPECT" as const,
			description: "Frota de veículos de luxo para transporte de convidados e noivos.",
			notes: "Em fase de pesquisa de mercado.",
			createdAt: daysAgo(20),
		},
		{
			id: "vnd_wedding_007",
			eventId: EVENTS.WEDDING,
			name: "Segurança VIP",
			category: "SECURITY" as const,
			phone: "+244 978 901 234",
			email: "contratos@segurancavip.ao",
			address: "Rua da Missão, Luanda",
			status: "CONTACTED" as const,
			description: "Serviço de segurança privada para eventos de alto perfil.",
			notes: "Contactados — a definir número de vigilantes.",
			createdAt: daysAgo(25),
		},
		{
			id: "vnd_wedding_008",
			eventId: EVENTS.WEDDING,
			name: "Eventos & Entretenimento",
			category: "ENTERTAINMENT" as const,
			phone: "+244 989 012 345",
			email: "events@eventosentretenimento.ao",
			address: "Rua dos Mártires, Luanda",
			status: "PROSPECT" as const,
			description: "Animação, jogos e atividades interativas para convidados.",
			notes: "Orçamento solicitado.",
			createdAt: daysAgo(15),
		},

		// ── EVENTS.ENGAGEMENT (4 vendors) ───────────────────────────────
		{
			id: "vnd_engag_001",
			eventId: EVENTS.ENGAGEMENT,
			name: "Doce Momento — Pastelaria",
			category: "CAKE" as const,
			phone: "+244 921 234 567",
			email: "encomendas@docemomento.ao",
			address: "Rua dos Enganos, Luanda",
			status: "CONTRACTED" as const,
			description: "Pastelaria artesanal com bolos personalizados para noivados.",
			notes: "Bolo de 3 andares com tema floral confirmado.",
			createdAt: daysAgo(40),
		},
		{
			id: "vnd_engag_002",
			eventId: EVENTS.ENGAGEMENT,
			name: "Som Ambiente — Eventos",
			category: "ENTERTAINMENT" as const,
			phone: "+244 932 345 678",
			email: "reservas@somambiente.ao",
			address: "Rua Comandante Gika, Luanda",
			status: "CONTRACTED" as const,
			description: "DJ e sistema de som profissional para festas íntimas.",
			notes: "Contrato assinado — equipamento de som incluído.",
			createdAt: daysAgo(38),
		},
		{
			id: "vnd_engag_003",
			eventId: EVENTS.ENGAGEMENT,
			name: "Floristas do Miramar",
			category: "DECORATION" as const,
			phone: "+244 943 456 789",
			email: "info@floristasmiramar.ao",
			address: "Miramar, Luanda",
			status: "CONTRACTED" as const,
			description: "Arranjos florais e decoração de mesas para noivados.",
			notes: "Tema pastel confirmado — flores naturais.",
			createdAt: daysAgo(36),
		},
		{
			id: "vnd_engag_004",
			eventId: EVENTS.ENGAGEMENT,
			name: "Foto Rápido",
			category: "PHOTOGRAPHY" as const,
			phone: "+244 954 567 890",
			email: "fotos@fotorapido.ao",
			address: "Rua da Resistência, Luanda",
			status: "NEGOTIATING" as const,
			description: "Serviço fotográfico rápido com entrega em 48h.",
			notes: "Proposta em análise — deseja antecipar pagamento.",
			createdAt: daysAgo(32),
		},

		// ── EVENTS.BIRTHDAY (3 vendors) ─────────────────────────────────
		{
			id: "vnd_birth_001",
			eventId: EVENTS.BIRTHDAY,
			name: "Restaurante O Cantinho",
			category: "CATERING" as const,
			phone: "+244 925 678 901",
			email: "eventos@ocantinho.ao",
			address: "Rua Comandante Gika, Luanda",
			status: "CONTRACTED" as const,
			description: "Restaurante tradicional angolano com serviço de catering.",
			notes: "Buffet para 50 pessoas — pratos tradicionais.",
			createdAt: daysAgo(10),
		},
		{
			id: "vnd_birth_002",
			eventId: EVENTS.BIRTHDAY,
			name: "DJ Festas",
			category: "MUSIC" as const,
			phone: "+244 936 789 012",
			email: "djf@djfestas.ao",
			address: "Rua dos Mártires, Luanda",
			status: "CONTRACTED" as const,
			description: "DJ especializado em festas de aniversário e celebrações.",
			notes: "Contrato confirmado — playlist a definir.",
			createdAt: daysAgo(8),
		},
		{
			id: "vnd_birth_003",
			eventId: EVENTS.BIRTHDAY,
			name: "Decorações Rápidas",
			category: "DECORATION" as const,
			phone: "+244 947 890 123",
			email: "decoracao@decoracoesrapidas.ao",
			address: "Rua 5 de Outubro, Luanda",
			status: "CONTRACTED" as const,
			description: "Decoração temática para festas de aniversário com entregas rápidas.",
			notes: "Tema festa surpresa — cores verde e dourado.",
			createdAt: daysAgo(6),
		},

		// ── EVENTS.CONFERENCE (6 vendors) ───────────────────────────────
		{
			id: "vnd_conf_001",
			eventId: EVENTS.CONFERENCE,
			name: "Centro de Convenções",
			category: "VENUE" as const,
			phone: "+244 928 901 234",
			email: "reservas@convencoes.ao",
			address: "Marginal da Luanda, Luanda",
			status: "COMPLETED" as const,
			description: "Espaço amplo para conferências com equipamento AV integrado.",
			notes: "Aluguer concluído — feedback positivo.",
			createdAt: daysAgo(90),
		},
		{
			id: "vnd_conf_002",
			eventId: EVENTS.CONFERENCE,
			name: "Catering Profissional",
			category: "CATERING" as const,
			phone: "+244 939 012 345",
			email: "catering@profissional.ao",
			address: "Rua da Missão, Luanda",
			status: "COMPLETED" as const,
			description: "Serviço de catering corporativo para conferências e seminários.",
			notes: "Coffee breaks e almoço buffet entregues com sucesso.",
			createdAt: daysAgo(88),
		},
		{
			id: "vnd_conf_003",
			eventId: EVENTS.CONFERENCE,
			name: "AV Tech Solutions",
			category: "OTHER" as const,
			phone: "+244 950 123 456",
			email: "solucoes@avtech.ao",
			address: "Rua dos Enganos, Luanda",
			status: "COMPLETED" as const,
			description: "Aluguer de equipamento audiovisual para eventos profissionais.",
			notes: "Projetores, ecrãs e sistema de som instalados.",
			createdAt: daysAgo(85),
		},
		{
			id: "vnd_conf_004",
			eventId: EVENTS.CONFERENCE,
			name: "Fotografia Corporativa",
			category: "PHOTOGRAPHY" as const,
			phone: "+244 961 234 567",
			email: "corporativo@fotocorp.ao",
			address: "Rua Major Kanhangulo, Luanda",
			status: "COMPLETED" as const,
			description: "Cobertura fotográfica profissional para eventos corporativos.",
			notes: "Entrega de fotos editadas concluída.",
			createdAt: daysAgo(82),
		},
		{
			id: "vnd_conf_005",
			eventId: EVENTS.CONFERENCE,
			name: "Segurança Total",
			category: "SECURITY" as const,
			phone: "+244 972 345 678",
			email: "seguranca@segurançatotal.ao",
			address: "Rua 5 de Outubro, Luanda",
			status: "COMPLETED" as const,
			description: "Serviço de segurança profissional para eventos corporativos.",
			notes: "Equipa de 8 vigilantes contratada — serviço concluído.",
			createdAt: daysAgo(80),
		},
		{
			id: "vnd_conf_006",
			eventId: EVENTS.CONFERENCE,
			name: "Transportes Executivos",
			category: "TRANSPORT" as const,
			phone: "+244 983 456 789",
			email: "reservas@transportesexec.ao",
			address: "Estrada de Catete, Luanda",
			status: "COMPLETED" as const,
			description: "Transporte executivo de convidados e palestrantes.",
			notes: "Viaturas executivas entregues — serviço concluído.",
			createdAt: daysAgo(78),
		},

		// ── EVENTS.WEDDING_CANCELLED (4 vendors) ────────────────────────
		{
			id: "vnd_wcancel_001",
			eventId: EVENTS.WEDDING_CANCELLED,
			name: "Palácio da Facunda",
			category: "VENUE" as const,
			phone: "+244 924 567 890",
			email: "reservas@palaciofacunda.ao",
			address: "Estrada da Facunda, Luanda",
			status: "CANCELLED" as const,
			description: "Espaço de eventos de luxo com jardim e salão principal.",
			notes: "Contrato cancelado — reembolso parcial processado.",
			createdAt: daysAgo(120),
		},
		{
			id: "vnd_wcancel_002",
			eventId: EVENTS.WEDDING_CANCELLED,
			name: "Decora Angola",
			category: "DECORATION" as const,
			phone: "+244 935 678 901",
			email: "decoracao@decoraangola.ao",
			address: "Rua da Resistência, Luanda",
			status: "CANCELLED" as const,
			description: "Decoração de eventos com tema angolano tradicional.",
			notes: "Cancelado — sem reembolso por antecipação.",
			createdAt: daysAgo(115),
		},
		{
			id: "vnd_wcancel_003",
			eventId: EVENTS.WEDDING_CANCELLED,
			name: "Chef Premium",
			category: "CATERING" as const,
			phone: "+244 946 789 012",
			email: "eventos@chefpremium.ao",
			address: "Rua dos Mártires, Luanda",
			status: "CANCELLED" as const,
			description: "Catering de alta gastronomia para casamentos e eventos de gala.",
			notes: "Cancelado — multa de 20% aplicada.",
			createdAt: daysAgo(110),
		},
		{
			id: "vnd_wcancel_004",
			eventId: EVENTS.WEDDING_CANCELLED,
			name: "Som & Luz",
			category: "MUSIC" as const,
			phone: "+244 957 890 123",
			email: "contacto@someluz.ao",
			address: "Rua Comandante Gika, Luanda",
			status: "CANCELLED" as const,
			description: "Sistema de som e iluminação profissional para casamentos.",
			notes: "Cancelado — reembolso integral efetuado.",
			createdAt: daysAgo(105),
		},

		// ── EVENTS.CORPORATE (3 vendors) ────────────────────────────────
		{
			id: "vnd_corp_001",
			eventId: EVENTS.CORPORATE,
			name: "Hotel Epic Sana",
			category: "VENUE" as const,
			phone: "+244 929 012 345",
			email: "eventos@epicsana.ao",
			address: "Rua da Missão, Luanda",
			status: "CONTRACTED" as const,
			description: "Hotel de 5 estrelas com salão de eventos e serviço premium.",
			notes: "Sala reservada — jantar corporativo para 80 pessoas.",
			createdAt: daysAgo(20),
		},
		{
			id: "vnd_corp_002",
			eventId: EVENTS.CORPORATE,
			name: "Catering Executivo",
			category: "CATERING" as const,
			phone: "+244 940 123 456",
			email: "executivo@cateringexec.ao",
			address: "Rua 5 de Outubro, Luanda",
			status: "CONTRACTED" as const,
			description: "Catering executivo com menu gourmet para eventos corporativos.",
			notes: "Menu internacional com opções vegetarianas confirmado.",
			createdAt: daysAgo(18),
		},
		{
			id: "vnd_corp_003",
			eventId: EVENTS.CORPORATE,
			name: "Banda Corporate",
			category: "MUSIC" as const,
			phone: "+244 951 234 567",
			email: "bandas@corporateband.ao",
			address: "Rua dos Enganos, Luanda",
			status: "NEGOTIATING" as const,
			description: "Banda instrumental para eventos corporativos — jazz e bossa nova.",
			notes: "Proposta recebida — aguardando aprovação do orçamento.",
			createdAt: daysAgo(16),
		},

		// ── EVENTS.WORKSHOP (2 vendors) ─────────────────────────────────
		{
			id: "vnd_work_001",
			eventId: EVENTS.WORKSHOP,
			name: "Hub de Criatividade",
			category: "VENUE" as const,
			phone: "+244 962 345 678",
			email: "reservas@hubcriatividade.ao",
			address: "Rua Comandante Gika, Luanda",
			status: "CONTRACTED" as const,
			description: "Espaço coworking e eventos para workshops e formações.",
			notes: "Espaço reservado para 40 participantes com equipamento AV.",
			createdAt: daysAgo(25),
		},
		{
			id: "vnd_work_002",
			eventId: EVENTS.WORKSHOP,
			name: "Coffee Break Express",
			category: "CATERING" as const,
			phone: "+244 973 456 789",
			email: "encomendas@coffeebreak.ao",
			address: "Rua dos Mártires, Luanda",
			status: "CONTRACTED" as const,
			description: "Serviço de coffee break para workshops e eventos de formação.",
			notes: "Café, chá, pastéis e frutas para 40 pessoas.",
			createdAt: daysAgo(22),
		},

		// ── EVENTS.BABY_SHOWER (2 vendors) ──────────────────────────────
		{
			id: "vnd_baby_001",
			eventId: EVENTS.BABY_SHOWER,
			name: "Jardim da Tia Graça",
			category: "VENUE" as const,
			phone: "+244 984 567 890",
			email: "festas@jardimtiagraça.ao",
			address: "Rua 5 de Outubro, Luanda",
			status: "COMPLETED" as const,
			description: "Jardim encantado para festas íntimas e embalar bebés.",
			notes: "Evento concluído com sucesso — espaço encantador.",
			createdAt: daysAgo(50),
		},
		{
			id: "vnd_baby_002",
			eventId: EVENTS.BABY_SHOWER,
			name: "Doces & Bolos",
			category: "CAKE" as const,
			phone: "+244 995 678 901",
			email: "encomendas@docesebolos.ao",
			address: "Rua da Resistência, Luanda",
			status: "COMPLETED" as const,
			description: "Confeitaria artesanal com bolos temáticos para baby showers.",
			notes: "Bolo temático rosa e branco entregue no prazo.",
			createdAt: daysAgo(48),
		},

		// ── EVENTS.CEREMONY (5 vendors) ─────────────────────────────────
		{
			id: "vnd_cere_001",
			eventId: EVENTS.CEREMONY,
			name: "Igreja de São Pedro",
			category: "VENUE" as const,
			phone: "+244 926 789 012",
			email: "paroquia@sampaio.ao",
			address: "Rua dos Mártires, Luanda",
			status: "CONTRACTED" as const,
			description: "Igreja histórica no centro da cidade — cerimónias religiosas.",
			notes: "Cerimónia reservada — horário confirmado com a paróquia.",
			createdAt: daysAgo(70),
		},
		{
			id: "vnd_cere_002",
			eventId: EVENTS.CEREMONY,
			name: "Flores da Igreja",
			category: "DECORATION" as const,
			phone: "+244 937 890 123",
			email: "flores@floresdaigreja.ao",
			address: "Rua Major Kanhangulo, Luanda",
			status: "CONTACTED" as const,
			description: "Decoração floral sagrada para cerimónias religiosas.",
			notes: "Contactada — aguardando orçamento detalhado.",
			createdAt: daysAgo(65),
		},
		{
			id: "vnd_cere_003",
			eventId: EVENTS.CEREMONY,
			name: "Cerimonial Eventos",
			category: "OTHER" as const,
			phone: "+244 948 901 234",
			email: "cerimonial@cerimonialeventos.ao",
			address: "Rua dos Enganos, Luanda",
			status: "NEGOTIATING" as const,
			description: "Cerimonial profissional para cerimónias religiosas e civis.",
			notes: "Proposta em negociação — valores em revisão.",
			createdAt: daysAgo(60),
		},
		{
			id: "vnd_cere_004",
			eventId: EVENTS.CEREMONY,
			name: "Fotógrafo Paroquial",
			category: "PHOTOGRAPHY" as const,
			phone: "+244 959 012 345",
			email: "foto@paroquial.ao",
			address: "Rua 5 de Outubro, Luanda",
			status: "PROSPECT" as const,
			description: "Fotógrafo especializado em cerimónias religiosas.",
			notes: "Em pesquisa — recomendado pela paróquia.",
			createdAt: daysAgo(55),
		},
		{
			id: "vnd_cere_005",
			eventId: EVENTS.CEREMONY,
			name: "Catering Paroquial",
			category: "CATERING" as const,
			phone: "+244 970 123 456",
			email: "catering@paroquial.ao",
			address: "Rua da Missão, Luanda",
			status: "NEGOTIATING" as const,
			description: "Serviço de catering para recepções pós-cerimónia na sala paroquial.",
			notes: "Em negociação — a definir número de convidados.",
			createdAt: daysAgo(50),
		},
	];

	for (const v of vendors) {
		await prisma.vendor.upsert({
			where: { id: v.id },
			update: {},
			create: v,
		});
	}

	// ── Vendor Contracts ──────────────────────────────────────────────
	const contracts = [
		// Wedding contracts
		{
			id: "ctr_001",
			eventId: EVENTS.WEDDING,
			vendorId: "vnd_wedding_001",
			number: "CNT-2026-001",
			startDate: daysAgo(45),
			endDate: monthsAhead(4),
			amount: 850000,
			status: "ACTIVE" as const,
			notes: "Decoração completa — tema botânico.",
			createdAt: daysAgo(45),
		},
		{
			id: "ctr_002",
			eventId: EVENTS.WEDDING,
			vendorId: "vnd_wedding_002",
			number: "CNT-2026-002",
			startDate: daysAgo(40),
			endDate: monthsAhead(4),
			amount: 1200000,
			status: "ACTIVE" as const,
			notes: "Catering completo — 250 convidados.",
			createdAt: daysAgo(40),
		},
		{
			id: "ctr_003",
			eventId: EVENTS.WEDDING,
			vendorId: "vnd_wedding_004",
			number: "CNT-2026-003",
			startDate: daysAgo(35),
			endDate: monthsAhead(4),
			amount: 650000,
			status: "ACTIVE" as const,
			notes: "Pacote fotográfico completo com vídeo.",
			createdAt: daysAgo(35),
		},

		// Engagement contracts
		{
			id: "ctr_004",
			eventId: EVENTS.ENGAGEMENT,
			vendorId: "vnd_engag_001",
			number: "CNT-2026-004",
			startDate: daysAgo(30),
			endDate: monthsAhead(1),
			amount: 180000,
			status: "ACTIVE" as const,
			notes: "Bolo de noivado e doces para 120 convidados.",
			createdAt: daysAgo(30),
		},
		{
			id: "ctr_005",
			eventId: EVENTS.ENGAGEMENT,
			vendorId: "vnd_engag_002",
			number: "CNT-2026-005",
			startDate: daysAgo(28),
			endDate: monthsAhead(1),
			amount: 150000,
			status: "ACTIVE" as const,
			notes: "DJ + sistema de som para noivado.",
			createdAt: daysAgo(28),
		},
		{
			id: "ctr_006",
			eventId: EVENTS.ENGAGEMENT,
			vendorId: "vnd_engag_003",
			number: "CNT-2026-006",
			startDate: daysAgo(26),
			endDate: monthsAhead(1),
			amount: 200000,
			status: "ACTIVE" as const,
			notes: "Decoração floral — mesas e ambiente.",
			createdAt: daysAgo(26),
		},

		// Birthday contracts
		{
			id: "ctr_007",
			eventId: EVENTS.BIRTHDAY,
			vendorId: "vnd_birth_001",
			number: "CNT-2026-007",
			startDate: daysAgo(5),
			endDate: new Date(),
			amount: 120000,
			status: "ACTIVE" as const,
			notes: "Buffet para 50 convidados.",
			createdAt: daysAgo(5),
		},
		{
			id: "ctr_008",
			eventId: EVENTS.BIRTHDAY,
			vendorId: "vnd_birth_002",
			number: "CNT-2026-008",
			startDate: daysAgo(4),
			endDate: new Date(),
			amount: 80000,
			status: "ACTIVE" as const,
			notes: "DJ para festa de aniversário.",
			createdAt: daysAgo(4),
		},
		{
			id: "ctr_009",
			eventId: EVENTS.BIRTHDAY,
			vendorId: "vnd_birth_003",
			number: "CNT-2026-009",
			startDate: daysAgo(3),
			endDate: new Date(),
			amount: 65000,
			status: "ACTIVE" as const,
			notes: "Decoração temática completa.",
			createdAt: daysAgo(3),
		},

		// Corporate contracts
		{
			id: "ctr_010",
			eventId: EVENTS.CORPORATE,
			vendorId: "vnd_corp_001",
			number: "CNT-2026-010",
			startDate: daysAgo(15),
			endDate: daysAhead(14),
			amount: 950000,
			status: "ACTIVE" as const,
			notes: "Sala de eventos + serviço de hotel para 80 convidados.",
			createdAt: daysAgo(15),
		},
		{
			id: "ctr_011",
			eventId: EVENTS.CORPORATE,
			vendorId: "vnd_corp_002",
			number: "CNT-2026-011",
			startDate: daysAgo(12),
			endDate: daysAhead(14),
			amount: 450000,
			status: "ACTIVE" as const,
			notes: "Jantar executivo para 80 pessoas.",
			createdAt: daysAgo(12),
		},

		// Workshop contracts
		{
			id: "ctr_012",
			eventId: EVENTS.WORKSHOP,
			vendorId: "vnd_work_001",
			number: "CNT-2026-012",
			startDate: daysAgo(20),
			endDate: daysAhead(21),
			amount: 280000,
			status: "ACTIVE" as const,
			notes: "Espaço para workshop — 40 participantes.",
			createdAt: daysAgo(20),
		},
		{
			id: "ctr_013",
			eventId: EVENTS.WORKSHOP,
			vendorId: "vnd_work_002",
			number: "CNT-2026-013",
			startDate: daysAgo(18),
			endDate: daysAhead(21),
			amount: 45000,
			status: "ACTIVE" as const,
			notes: "Coffee break para 40 participantes.",
			createdAt: daysAgo(18),
		},

		// Ceremony contracts
		{
			id: "ctr_014",
			eventId: EVENTS.CEREMONY,
			vendorId: "vnd_cere_001",
			number: "CNT-2026-014",
			startDate: daysAgo(60),
			endDate: monthsAhead(5),
			amount: 350000,
			status: "ACTIVE" as const,
			notes: "Aluguer da igreja para cerimónia religiosa.",
			createdAt: daysAgo(60),
		},
	];

	for (const c of contracts) {
		await prisma.vendorContract.upsert({
			where: { id: c.id },
			update: {},
			create: c,
		});
	}

	// ── Count vendors per event ────────────────────────────────────────
	const counts: Record<string, number> = {};
	for (const v of vendors) {
		counts[v.eventId] = (counts[v.eventId] || 0) + 1;
	}

	const eventLabels: Record<string, string> = {
		[EVENTS.WEDDING]: "Casamento Ana & Carlos",
		[EVENTS.ENGAGEMENT]: "Noivado Beatriz & David",
		[EVENTS.BIRTHDAY]: "Aniversário de Ricardo",
		[EVENTS.CONFERENCE]: "Conferência TechAngola 2026",
		[EVENTS.WEDDING_CANCELLED]: "Casamento Silva & Santos",
		[EVENTS.CORPORATE]: "Jantar Corporativo",
		[EVENTS.WORKSHOP]: "Workshop de Criatividade",
		[EVENTS.BABY_SHOWER]: "Festa de Embalar da Maria",
		[EVENTS.CEREMONY]: "Cerimónia Religiosa de São Pedro",
	};

	console.log(`  ✅ Vendors (${vendors.length})`);
	for (const [eventId, count] of Object.entries(counts)) {
		console.log(`    • ${eventLabels[eventId] || eventId}: ${count} fornecedores`);
	}
	console.log(`  ✅ Vendor Contracts (${contracts.length})`);

	return { vendors, contracts };
}
